config/routes.rb
Rails.application.routes.draw do
  resources :service_histories
  resources :customers
  resources :posts
  root to: 'pages#home'
  devise_for :users
  
  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  post 'service_histories/checkout'
  
  resources :products

  resources :customers do
    resources :service_histories
  end

  # resources :carts do
  #   resources :service_histories
  # end
  
  #root 'products#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  has_many :service_histories
  
  has_many :products ,through: :service_histories

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    if current_user.admin==true 
      @customers = Customer.all
    else
      @customers = Customer.where(user_id: current_user.id)
    end
   
    @service_histories=ServiceHistory.all
 
    # @customer = Customer.new
  end

  # GET /customers/1 or /customers/1.json
  def show

  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:name, :email, :phone, :DOB, :address, :vehicle_type, :vehicle_number, :user_id)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
 

</div>
<div class="jumbotron">
  <h1 class="display-4"><%= customer.name %></h1> 
  <p class="lead"><strong>email: </strong> <%= customer.email %></p>
  <hr class="lead">
  <p class="lead"> <strong>Phone no: </strong>  <%= customer.phone  %></p>
  <p class="lead"> <strong>DOB:</strong>  <%= customer.DOB  %>   </p>
  <p class="lead">   <strong> Address: </strong> <%= customer.address  %> </p>
  <p class="lead"><strong> Vehicle Type: </strong> <%= customer.vehicle_type  %>   </p>
  <p class="lead"><strong> Vehicle Number: </strong> <%= customer.vehicle_number  %>   </p>
</div>

app/views/customers/_form.html.erb
<style> 
.text {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  box-sizing: border-box;
  border: 2px solid #17a2b8;
  border-radius: 4px;
}
</style>

<%= form_with(model: customer) do |form| %>
  <% if customer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class:"form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name , style: "class: text"%>
  </div>
  <%= current_user.id%>
  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.hidden_field :user_id, value: current_user.id  %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :DOB, style: "display: block" %>
    <%= form.date_field :DOB %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :vehicle_type, style: "display: block" %>
    <%# <%= form.text_field :vehicle_type %> 
    <%= form.radio_button :vehicle_type, "car" %> Car<br>
    <%= form.radio_button :vehicle_type, "bike" %> Bike<br>
    <%= form.radio_button :vehicle_type, "bus" %> Bus
  </div>

  <div>
    <%= form.label :vehicle_number, style: "display: block" %>
    <%= form.text_field :vehicle_number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<style>
.cc {
  margin: 10px;
  width: 40%;
  border: 5px solid #73AD21;
  padding: 30px;
}
</style>

<div class="cc">
<%= render "form", customer: @customer %>
</div>
<br>

<div>
  <%= link_to "Show this customer", @customer %> |
  <%= link_to "Back to customers", customers_path %>
</div>

app/views/customers/index.html.erb
<p style="color: green"><%= notice %></p>







<%# 
  <% @users.each do |customer| %>
    <%# <%= render customer %>
    <%# <p>
      <%= link_to "Show this customer", customer %>
    <%# </p>
  <% end %> 

<%  if current_user && current_user.admin %>

<h1>Customers</h1>

<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      
  
    <th>Customer name</th>
    <th>Email</th>
    <th>Phone</th>
   
    <th>address</th>
    <th>Date of Birth</th>
    <th>vehicle_type</th>

    <th>vehicle_number</th>
    <th>More</th>
  
    </tr>
    </thead>

<tbody>



  <% @customers.each do |customer| %>
    <tr>
     <td><%= customer.name%></td>
      <td><%= customer.email %></td>
      <td><<%= customer.phone %></td>
      <td> <%= customer.address %></td>
      <td><<%= customer.DOB %></td>
      <td><%= customer.vehicle_type %></td>
      <td><%= customer.vehicle_number %></td>
      
      
      
      <td><%= link_to "Show this customer", customer %></td>
      <% end %>
      <% end %>
    </tr>
    <tbody>
      

</table>

 <%  if current_user && !current_user.admin %>
    <% @customers.each do |customer| %>

    </div>
<div class="jumbotron">
  <h1 class="display-4"><%= customer.name %></h1> 
  <p class="lead"><strong>email: </strong> <%= customer.email %></p>
  <hr class="lead">
  <p class="lead"> <strong>Phone no: </strong>  <%= customer.phone  %></p>
  <p class="lead"> <strong>DOB:</strong>  <%= customer.DOB  %>   </p>
  <p class="lead">   <strong> Address: </strong> <%= customer.address  %> </p>
  <p class="lead"><strong> Vehicle Type: </strong> <%= customer.vehicle_type  %>   </p>
  <p class="lead"><strong> Vehicle Number: </strong> <%= customer.vehicle_number  %>   </p>
</div>
    
      
      
  
      <%= link_to "Edit this customer", edit_customer_path(customer), class:"btn btn-success" %> 
     
      <% end %>
      <% end %>
      
   
    </tr>

 <%  if current_user && current_user.admin  %>
<%= link_to "New customer", new_customer_path %>
<% end %>

app/views/customers/new.html.erb
<style> 

.cc {
  margin: 10px;
  width: 40%;
  border: 5px solid #73AD21;
  padding: 30px;
}
</style>

<div class="cc">
<h1>Dashboard</h1>



<%= render "form", customer: @customer %>

<br>

<div>
 <%  if current_user && current_user.admin  %>
  <%= link_to "Back to customers", customers_path %>
  <% end %>
</div>
</div>

app/views/customers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @customer %>



 

  <%# <%= link_to "new" ,new_service_history_path %> 


   <%  if current_user && current_user.admin %>
   <%= link_to "Edit this customer", edit_customer_path(@customer), class:"btn btn-success" %> 
   <br>
   <br>
<%= button_to "Destroy this customer", @customer, method: :delete ,class:"btn btn-success" %>
<br>
  <%= link_to "Back to customers", customers_path %>
<% else %>
 <%= link_to "Edit My profile", edit_customer_path(@customer), class:"btn btn-success" %> 


<% end  %>
<br>
<br>
 <%= link_to "Select services", products_path %>|