config/routes.rb
Rails.application.routes.draw do
  resources :service_histories
  resources :customers
  resources :posts
  root to: 'pages#home'
  devise_for :users
  
  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  post 'service_histories/checkout'
  
  resources :products

  resources :customers do
    resources :service_histories
  end

  # resources :carts do
  #   resources :service_histories
  # end
  
  #root 'products#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/service_history.rb
class ServiceHistory < ApplicationRecord
  

  # 

  belongs_to :customer
  belongs_to :product

  has_one_attached :before
  has_one_attached :after
  # belongs_to :cart
  

  

  # def amount_due
  # #  @service_history.amount_paid - service_history.product.price 
  # @service_histories.amount_paid - @service_histor.product.price 
  # end


  # <%= @service_history.product.price %>
  
end

app/controllers/service_histories_controller.rb
class ServiceHistoriesController < ApplicationController
  
  before_action :set_service_history, only: %i[ show edit update destroy ]

  # GET /service_histories or /service_histories.json
  def index
    # @service_histories = ServiceHistory.where(customer_id: current_user.id)
    @orderables=Orderable.all
    if current_user.admin==true 
      @customers = Customer.all
    else
      @customers = Customer.where(user_id: current_user.id)
    end
    # @customers=Customer.all
    @users=current_user

    
    @users=User.all
    @service_histories=ServiceHistory.all
    a=Product.find_by(id: 1)
    
    @products=Product.all


    # if current_user.admin==true 
    #   @service_histories = ServiceHistory.all
    # else
    #   @service_histories = ServiceHistory.where(user_id: current_user.id)
    # end
  
  end

  # GET /service_histories/1 or /service_histories/1.json
  def show
    @service_histories = ServiceHistory.find(params[:id])
    @user=User.all
    # @customer = @service_histories.customers.all
    # @products=@service_history.products.all
     #@bookings=@car.bookings.all
     respond_to do |format|
      format.html
      format.pdf do
        pdf=ServiceHistoryPdf.new(@service_history)
        send_data pdf.render, filename: "Service_History#{@service_history.id}.pdf",
                              type: "application/pdf",
                              dispostion: "inline"
      end
    end
 

  end

  # GET /service_histories/new
  def new
    @service_history = ServiceHistory.new
    @users=current_user
    # @customers=Customer.all
    # b= @users.username   
    # @service_histories=ServiceHistory.all
    
  end

  # GET /service_histories/1/edit
  def edit
  end

  # POST /service_histories or /service_histories.json
  def create
    @service_history = ServiceHistory.new(service_history_params)

    # +++++++++++++++++++++++++++++++++++++++++++++++++++++
    # @customer = Customer.find(params[:customer_id])
    # @service_history = @customer.service_histories.create(service_history_params)
    # redirect_to article_path(@article)


      # +++++++++++++++++++++++++++++++++++++++++++++++++++++

    respond_to do |format|
      if @service_history.save
        format.html { redirect_to service_history_url(@service_history), notice: "Service history was successfully created." }
        format.json { render :show, status: :created, location: @service_history }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_histories/1 or /service_histories/1.json
  def update
    respond_to do |format|
      if @service_history.update(service_history_params)
        format.html { redirect_to service_history_url(@service_history), notice: "Service history was successfully updated." }
        format.json { render :show, status: :ok, location: @service_history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_histories/1 or /service_histories/1.json
  def destroy
    @service_history.destroy

    respond_to do |format|
      format.html { redirect_to service_histories_url, notice: "Service history was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_history
      @service_history = ServiceHistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_history_params
      params.require(:service_history).permit(:customer_id, :product_id, :cart_id, :startdate, :enddate, :status, :amount_paid, :amount_due, :before, :after ,:total)
    end
end

app/helpers/service_histories_helper.rb
module ServiceHistoriesHelper
end

app/views/service_histories/_form.html.erb
<%= form_with(model: service_history) do |form| %>
  <% if service_history.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(service_history.errors.count, "error") %> prohibited this service_history from being saved:</h2>

      <ul>
        <% service_history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  
  <div>
  <%  if current_user && current_user.admin  %>
    <%= form.label :customer_id, style: "display: block" %>
    <%# <%= form.hidden_field :customer_id , value: current_user.id %>
    <%= form.text_field :customer_id %>

      <% elsif current_user && !current_user.admin %>
      
    <%# <%= @users.customers.ids %> 
     <%# <% current_user.customers.each do |i|%>
      <%# <% mk= i.name %>
      <%# <% end %> 
      <%= form.hidden_field :customer_id , value: @users.customers.ids %>
  <% end %>
  </div>
  
 
   
    <%# <%= current_user.id %> 

  <div>
    <%# <%= form.label :product_id, style: "display: block" %> 
    <%= form.hidden_field :product_id, value:1 %>
       
  </div>
 

 
   <div>
     <%# <% cartttss= @cart.id %>
       <%# <%= cartttss  %> 
    <%= form.label :cart_id, style: "display: block" %>
    
    <%  if current_user && current_user.admin %>
    <%# <%= form.text_field :cart_id %> %>
    <%= form.hidden_field :cart_id , value: @cart.id%>

      <% elsif current_user && !current_user.admin %>
      <%# <%= @cart.id %> 
      <%= form.hidden_field :cart_id , value: @cart.id%>


    <% end %>
  
  </div>
   

  <div>
    <%= form.label :startdate, style: "display: block" %>
    <%= form.date_field :startdate %>
  </div>

  <div>
    <%= form.label :enddate, style: "display: block" %>
    <%= form.date_field :enddate %>
  </div>

  <div>
  
    <%= form.label :status, style: "display: block" %>

    <%  if current_user && current_user.admin %>
    <%= form.text_field :status %>
    
    <% else %>
    <%= form.hidden_field :status, value: "confirmed" %>
    
   
    <% end %>
  </div>


  

  <div>
    <%= form.label :amount_paid, style: "display: block" %>
    <%= form.text_field :amount_paid %> 
    <%# <%= form.hidden_field :cart_total , value: @cart.total%> <=
    <%= @cart.total %>

  </div>

  <%# <div>
    <%= form.label :amount_due, style: "display: block" %>
    <%# <%= form.hidden_field :amount_due %>
  <%# </div> %> 

   <div>
    <%= form.label :total, style: "display: block" %>
    <%= form.hidden_field  :total, value: @cart.total %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/service_histories/_service_history.html.erb
<div id="<%= dom_id service_history %>">
  
  <%# <p>
    <strong>Amount due:</strong>
     <%# <%= @service_history.amount_paid - @service_history.product.price %> 
   
  


  <%# <%= @service_history.product.price %> 

</div>

</div>
<div class="jumbotron">
  <h1 class="display-4">Service History</h1> 
  <hr class="lead">
  <p class="lead"><strong>Customer Id </strong> <%= service_history.customer_id %></p>
  
  <p class="lead"> <strong>Product Id </strong>  <%= service_history.product_id %></p>
  <p class="lead"> <strong>Start Date</strong>  <%= service_history.startdate %>  </p>
  <p class="lead">   <strong> Start enddate </strong> <%= service_history.enddate %> </p>
  <p class="lead"><strong> Status </strong> <%= service_history.status %>  </p>
  <p class="lead"><strong> Amound Paid </strong> <%= service_history.amount_paid %>   </p>




<table style="width:80%">
  <tr>
    <th>
    <% if service_history.before.attached? %>
  <%= image_tag service_history.before ,width:"600px" ,height:"400px" %>
  <% end %>
</th>
    <th>
     <% if service_history.after.attached? %>
  <%=  image_tag service_history.after ,width:"600px" ,height:"400px"%>
   <% end %>
    </th>
 
  </tr>
  
</table>


 
 
 
 </div>

app/views/service_histories/edit.html.erb
<h1>Editing service history</h1>


<%  if current_user && current_user.admin %>
<%= render "form", service_history: @service_history %>

<% end %>

<%  if current_user &&  current_user.usertype == 1 %>

<%= form_with(model: @service_history) do |form| %>
  <% if @service_history.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@service_history.errors.count, "error") %> prohibited this service_history from being saved:</h2>

      <ul>
        <% @service_history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div>
  <%= form.label :status, style: "display: block" %>
  <%= form.text_field :status %>
</div>


  <%  if current_user.usertype == 1 or current_user.admin  %>
  <%= form.label :before, style: "display: block" %>
  <%= form.file_field :before %>

      <%= form.label :after, style: "display: block" %>
  <%= form.file_field :after %>

<div>
    <%= form.submit %>
  </div>
<% end %>
    <% end %>
<% end %>




<br>

<div>
  <%= link_to "Show this service history", @service_history %> |
  <%= link_to "Back to service histories", service_histories_path %>
</div>

app/views/service_histories/index.html.erb
<p style="color: green"><%= notice %></p>
 <%# <br>
 <%= @service_histories.first.status %>
<%# <% current_user.customers.each do |i|%>
<%# <%= i.name %>
<%# <% end %>



<%# <%=  @current_user.customers.ids %>



<h1>Service histories</h1>
<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
   <th> Service History id </th>
    <th> customer_id </th>

    <th> customer Name</th>
    <th>Products details</th>

    <th>Start Date</th>
    <th>End Date </th>

    <th>status</th>
    
    <th>Total</th>
    <th>Amount Paid</th>
    <th>Amount Due</th>
   
    <th>details</th>
  
    </tr>
    </thead>

<tbody>


<%  if current_user && current_user.admin %>
  <% @service_histories.each do |service_history| %>
    <tr>
     <td><%= service_history.id %></td>
       <td><%= service_history.customer_id %></td>
     <td><%= service_history.customer.name %></td>
    <td>
      <% @orderables.each do |orderable| %>
         <% if orderable.cart_id==service_history.cart_id %>
         <% product = orderable.product %>
         <%= product.name %>
         <br>
      <% end %>
   <% end %>
     </td>

      <td><%= service_history.startdate %></td>
      <td><%= service_history.enddate %></td>

      <td><%= service_history.status %></td>
      <td><%= service_history.total %> </td> 
      <td><%= service_history.amount_paid %></td>
      <td>Rs. <%= service_history.total - service_history.amount_paid %></td>
      <td><%= link_to "Show this service history", service_history %></td>
      
    </tr>
      <% end %>

  <%  elsif current_user && !current_user.admin && current_user.usertype == 0 %>
  
 
     <% @service_histories.each do |service_history| %>
        <%# <%if service_history.customer_id == @current_user.customers.ids %> 
       
      <tr>
      <% if service_history.customer.name ==@current_user.username %> 
      <td><%= service_history.id %></td>
      <td><%= service_history.customer_id %></td>
      <td><%= service_history.customer.name %></td>


      <%# <td><%= service_history.product_id %>
      

 <td>
      <% @orderables.each do |orderable| %>
         <% if orderable.cart_id==service_history.cart_id %>
         <% product = orderable.product %>
         
         <%= product.name %>
         <br>
          <% end %>
  
    <% end %>
     </td>

      <td><%= service_history.startdate %></td>
      <td><%= service_history.enddate %></td>

      <td><%= service_history.status %></td>
      <%# <td><%= service_history.product.price %>
      <td><%= service_history.total %> </td> 
      <td><%= service_history.amount_paid %></td>
     
      <td><%= service_history.total-service_history.amount_paid  %></td>
      <td><%= link_to "Show this service history", service_history %></td>
      <% end %>
    
      <% end %>

       <% end %>

    </tr>


  </tbody>
  
</table>



    
  
</div>

<%  if current_user && current_user.admin %>
<%= link_to "New service history", new_service_history_path %>
<% end %>

<%# <p>Total: <%= @cart.total %>



  <%# <% @customers.each do |customer| %>
  <%# <tr>
    <td><%= customer.name %>

      <%# <%= current_user.id %> 
  <%# <%= @service_histories.customer.id %> 

 

   <%# <p>
    #   <%= link_to "Show this customer", customer %>
     <%# </p>
pe

 <%# current_user.id %>
 <% current_user.customers.name%>


 



 <%  if current_user && !current_user.admin && current_user.usertype == 1 %>
  <table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      
  <th> Services_history id</th>
    <th> customer Name</th>
  
 
    <th>Products details</th>
    <th>Start Date</th>
    <th>End Date </th>
    <th>status</th>
    
   
    <th>details</th>
  
    </tr>
    </thead>

<tbody>

  <br>

  <br>
  <br>
   <% @service_histories.each do |service_history| %>
   <% if service_history.id == 33 %>
    <tr>
     <td><%= service_history.id %></td>
     <td><%= service_history.customer.name %></td>
    
    
      <%# <td><%= service_history.product.name %>
      <%# <td><%= service_history.cart_id %></td> 

       <td>
      <% @orderables.each do |orderable| %>
         <% if orderable.cart_id==service_history.cart_id %>
         <% product = orderable.product %>
         
         <%= product.name %>
         <br>
          <% end %>
  
    <% end %>
     </td>
     
      <td><%= service_history.startdate %></td>
      <td><%= service_history.enddate %></td>

      <td><%= service_history.status %></td>
   

      
      
   
      <td><%= link_to "Show this service history", service_history %></td>
    </tr>
      <% end %>
        <% end %>
        <% end %>

app/views/service_histories/new.html.erb
<h1>New service history</h1>

<%# <%= render "form", service_history: @service_history %> 











<%= render "form", service_history: @service_history %>

<div>
  <%= link_to "Back to service histories", service_histories_path %>
</div>

app/views/service_histories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @service_history %>

<div>
  <%= link_to "Edit this service history", edit_service_history_path(@service_history) ,class:"btn btn-secondary"%> |
  <%= link_to "Destroy this service history", @service_history, method: :delete ,class:"btn btn-danger"%>
  <br>
  <br>
  <br>
  <%= link_to "Back to service histories", service_histories_path ,class:"btn btn-primary"%>

  
</div>
<br>
<%= link_to "Invoice", service_history_path(@service_history ,format:"pdf") ,class:"btn btn-primary"%>

  
     

   
 